version: 2



jobs:
  build:
    working_directory: ~/irflow_sdk_python
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install pytest
            pip install pytest-cov
            pip install awscli
            pip install coverage report
            pip install coveralls
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          working_directory: tests
          command: |
            source ../venv/bin/activate
            aws s3 cp s3://syncurity-ci/test_data.py .
            py.test --cov-config .coveragerc --cov ../
            coverage report
            coveralls

      - store_artifacts:
          path: test-reports/
          destination: tr1